name: ipydatagrid-test-ipw8
channels:
  - conda-forge
dependencies:
  - pip
  - python
  - nodejs=20
  - yarn
  - ipywidgets >=8.0.0,<9
  - traitlets >=4.3.0
  - traittypes >=0.0.6
  - numpy >=1.10.4,<2.0.0
  - pandas >=1.0.0,<2.0.0
  - bqplot
  - scipy
  - jupyterlab
  - jupyter-packaging
  - pytest
  - nbval
  - pytest-cov
  - selenium
  - flake8
  - nose
  - codespell
